[package]
name = "centraldogma"
version = "0.1.0"
authors = ["Hoang Luu <luu.hoang@linecorp.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10", features = ["json"] }
serde = "1.0"
thiserror = "1.0"
url = "2.1"
yup-oauth2 = "4.1"
tokio = { version = "0.2", features = ["rt-threaded"] }
